const express = require('express')
const chats = require('./routes/chats')
const register = require('./routes/register')
const login = require('./routes/login')
const auth = require('./middlewares/auth')
const jwt = require('./middlewares/JWT')
const refresh_token = require('./routes/regenerate_token')
const reset_password = require('./routes/reset_passwrod')
require('dotenv').config()

const app = express()
app.use('/chats', chats)
app.use('/register', register)
app.use('/login', login)
app.use('/refresh', refresh_token)
app.use('/reset_password', reset_password)
app.use(express.json())

app.listen(process.env.PORT, console.log(`listening on port ${process.env.PORT}...`))